import { DailyRecap } from './types'

// Contributi al brief per testata — usati per generare il brief filtrato
export const BRIEF_CONTRIBUTIONS: Record<string, string> = {
  'il-manifesto': 'Il Manifesto apre sull\'escalation israeliana in Libano ("dottrina Gaza") e sulle mosse militari USA contro l\'Iran, con un occhio alla mobilitazione sociale interna e agli Oscar.',
  'eldiario': 'elDiario.es è dominato dalle elezioni di Castiglia e León: vittoria del PP, Vox che rallenta, crollo di Podemos.',
  'el-salto': 'El Salto connette le elezioni spagnole alle violenze in Cisgiordania e alla guerra in Iran, con una nota sulla crisi degli affitti a Valencia.',
  'la-jornada': 'La Jornada denuncia le deportazioni forzate di migranti da parte di Trump e segue l\'Iran dalla prospettiva latinoamericana.',
  'the-guardian': 'The Guardian si concentra sull\'impatto africano del conflitto iraniano (catene di approvvigionamento, sanità tagliata) e restituisce un manufatto sacro alla Costa d\'Avorio.',
  'al-jazeera': 'Al Jazeera mappa lo Stretto di Hormuz, il Libano come leva negoziale israeliana e le ripercussioni energetiche della guerra.',
  'the-intercept': 'The Intercept denuncia i medici USA bloccati a Gaza dal blocco israeliano e la criminalizzazione dei manifestanti anti-ICE.',
  'jacobin': 'Jacobin pubblica un necrologio di Habermas, analizza la resa dei conti Epstein e critica l\'acquiescenza dell\'estrema destra europea agli USA.',
  '972-magazine': '+972 Magazine riporta dalla Cisgiordania sotto chiusura totale: coloni che approfittano della guerra e censura dei media israeliani.',
  'daily-maverick': 'Daily Maverick copre il massacro di Sharpeville a 66 anni, l\'inchiesta sull\'assassino di "Testimone D" e la crisi dei voli in Asia per l\'embargo sul carburante.',
}

const TODAY = '2026-03-16'

export const MOCK_RECAPS: DailyRecap[] = [
  {
    newspaper: { id:'1', slug:'il-manifesto', name:'Il Manifesto', country:'IT', region:'europa', language:'it', orientation:'sinistra', frequency:'daily', description:'Quotidiano comunista italiano, fondato nel 1971.', url:'https://ilmanifesto.it', rss_url:'https://ilmanifesto.it/feed/', scrape_method:'rss', topics:['politica','lavoro','diritti'], active:true },
    headlines: [
      { title:'Paul Thomas Anderson trionfa agli Oscar con 6 statuette', summary:"L'Academy incorona \"Una battaglia dopo l'altra\" come miglior film e miglior regia del 2025.", url:'https://ilmanifesto.it/paul-thomas-anderson-sbanca-gli-oscar-6-statuette', topic:'cultura', pubDate:`${TODAY}T08:00:00Z` },
      { title:'Soccorritori nel mirino, la dottrina Gaza applicata in Libano', summary:'Dodici tra personale medico e paramedico sono morti dopo che Israele ha colpito il centro medico in cui erano in servizio.', url:'https://ilmanifesto.it/target-soccorritori-la-dottrina-gaza-applicata-in-libano', topic:'conflitti', pubDate:`${TODAY}T07:30:00Z` },
      { title:'Peter Thiel, il nuovo mondo degli oligarchi "oltre" la democrazia', summary:'Peter Thiel come anello di congiunzione tra cristo nazionalismo e populismo di Trump.', url:'https://ilmanifesto.it/peter-thiel-il-nuovo-mondo-degli-oligarchi-oltre-la-democrazia', topic:'politica', pubDate:`${TODAY}T07:00:00Z` },
      { title:'20 mila persone per un "No sociale" al referendum e alla guerra', summary:'In 20mila hanno manifestato a Roma contro il referendum, la guerra e il governo liberticida.', url:'https://ilmanifesto.it/in-20-mila-per-un-no-sociale-al-referendum-e-alla-guerra', topic:'società', pubDate:`${TODAY}T06:45:00Z` },
      { title:'La FIFA del "re" è grande e Infantino è il suo profeta', summary:'I prossimi Mondiali di calcio saranno i più politici e politicizzati di sempre.', url:'https://ilmanifesto.it/la-fifa-del-king-e-grande-e-infantino-e-il-suo-profeta', topic:'società', pubDate:`${TODAY}T06:30:00Z` },
      { title:'Khark sotto attacco: Trump punta la spina dorsale dell\'Iran', summary:"L'operazione militare statunitense rivela una realtà più complessa del previsto.", url:'https://ilmanifesto.it/khark-sotto-attacco-trump-punta-la-spina-dorsale-delliran', topic:'geopolitica', pubDate:`${TODAY}T06:00:00Z` },
      { title:'Il fermo di Sea-Eye 5 era illegittimo. Viminale condannato', summary:'Il tribunale di Ragusa dichiara illegittimo il fermo della nave umanitaria, condannando il Ministero dell\'Interno.', url:'https://ilmanifesto.it/il-fermo-di-sea-eye-5-era-illegittimo-viminale-condannato', topic:'diritti', pubDate:`${TODAY}T05:45:00Z` },
      { title:'Immobili e divisi: scontro nel governo sul petrolio russo', summary:'Il governo italiano mostra profonde divisioni sulla questione del petrolio russo.', url:'https://ilmanifesto.it/immobili-e-divisi-scontro-nel-governo-sul-petrolio-russo', topic:'politica', pubDate:`${TODAY}T05:30:00Z` },
      { title:'Francia: l\'estrema destra tasta il terreno nelle municipali', summary:'Alle elezioni comunali francesi, la destra si misura per la prima volta su scala locale dopo l\'omicidio di Deranque.', url:'https://ilmanifesto.it/francia-estrema-destra-municipali', topic:'politica', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Lavoro povero: il paradosso dei contratti pirata che crescono', summary:'Nonostante l\'occupazione in aumento, i contratti pirata proliferano erodendo i salari minimi di settore.', url:'https://ilmanifesto.it/lavoro-povero-contratti-pirata', topic:'lavoro', pubDate:`${TODAY}T04:30:00Z` },
    ]
  },
  {
    newspaper: { id:'4', slug:'eldiario', name:'elDiario.es', country:'ES', region:'europa', language:'es', orientation:'progressista', frequency:'daily', description:'Digitale spagnolo reader-funded. Progressista, modello sostenibile.', url:'https://www.eldiario.es', rss_url:'https://www.eldiario.es/rss/', scrape_method:'rss', topics:['politica','economia','società','diritti'], active:true },
    headlines: [
      { title:'Abascal esige al PP di formare coalizioni con Vox in Castiglia e León, Estremadura e Aragona', summary:'Il leader di Vox chiede al PP di siglare accordi di governo nelle tre regioni dove è possibile una maggioranza di destra.', url:'https://www.eldiario.es/politica/abascal-exige-pp-coaliciones-vox_1_13071736.html', topic:'politica', pubDate:`${TODAY}T09:00:00Z` },
      { title:'Feijóo chiede ad Abascal di sbloccare Estremadura, Aragona e Castiglia e León', summary:'Il leader del PP esorta Abascal a raggiungere accordi regionali, avvertendo contro il rischio di blocchi.', url:'https://www.eldiario.es/politica/feijoo-pide-abascal-desbloquee_1_13071807.html', topic:'politica', pubDate:`${TODAY}T08:30:00Z` },
      { title:'Vince il PP, si riprende il PSOE, Vox raggiunge il suo culmine', summary:"Analisi post-elettorale: vittoria del PP, ripresa del PSOE, e Vox al suo picco di consensi.", url:'https://www.eldiario.es/escolar/gana-pp-recupera-psoe-vox-toca-techo_132_13070552.html', topic:'politica', pubDate:`${TODAY}T08:00:00Z` },
      { title:'Podemos dopo la debacle in Castiglia e León: "Il nostro risultato è nefasto"', summary:"La dirigenza di Podemos ammette la gravità dei risultati e annuncia una profonda riflessione interna.", url:'https://www.eldiario.es/castilla-y-leon/debacle-castilla-leon-resultado-nefasto_1_13071331.html', topic:'politica', pubDate:`${TODAY}T07:45:00Z` },
      { title:'Che modo di perdere', summary:"Critica alla gestione del PP nei confronti di Vox, con la loro difficile relazione politica.", url:'https://www.eldiario.es/opinion/zona-critica/manera-perder_129_13070424.html', topic:'politica', pubDate:`${TODAY}T07:30:00Z` },
      { title:'Mañueco apre la porta a governare con Vox e definisce "buono" il patto del 2022', summary:'Il presidente della Castiglia e León si dice disponibile a ripetere l\'accordo di governo con Vox.', url:'https://www.eldiario.es/castilla-y-leon/manueco-abre-gobernar-vox_1_13071500.html', topic:'politica', pubDate:`${TODAY}T07:00:00Z` },
      { title:'La guerra in Iran fa schizzare i prezzi dell\'energia in Spagna', summary:'Il conflitto nello Stretto di Hormuz impatta le forniture di gas spagnolo: prezzo in rialzo del 18% in una settimana.', url:'https://www.eldiario.es/economia/guerra-iran-energia-espana_1_13071600.html', topic:'economia', pubDate:`${TODAY}T06:30:00Z` },
      { title:'Il governo spagnolo stanzia 200 milioni per l\'accoglienza dei rifugiati iraniani', summary:'Sánchez annuncia un pacchetto di emergenza per l\'accoglienza di circa 15.000 rifugiati iraniani attesi nei prossimi mesi.', url:'https://www.eldiario.es/politica/gobierno-espanol-refugiados-iranies_1_13071700.html', topic:'migrazioni', pubDate:`${TODAY}T06:00:00Z` },
      { title:'Yolanda Díaz: "La sinistra deve tornare a parlare di classe lavoratrice"', summary:"La ministra del lavoro apre il dibattito interno alla coalizione sull'identità della sinistra spagnola.", url:'https://www.eldiario.es/politica/yolanda-diaz-sinistra-classe-lavoratrice_1_13071800.html', topic:'lavoro', pubDate:`${TODAY}T05:30:00Z` },
      { title:'Clima: la Spagna registra il febbraio più caldo della storia', summary:'Il mese scorso ha segnato un record di temperature con 2,8°C sopra la media storica in tutta la penisola.', url:'https://www.eldiario.es/medioambiente/spagna-febbraio-record-caldo_1_13071900.html', topic:'clima', pubDate:`${TODAY}T05:00:00Z` },
    ]
  },
  {
    newspaper: { id:'6', slug:'el-salto', name:'El Salto', country:'ES', region:'europa', language:'es', orientation:'sinistra', frequency:'daily', description:'Cooperativa giornalistica spagnola. Movimenti sociali, ecologismo, femminismo.', url:'https://www.elsaltodiario.com', rss_url:null, scrape_method:'jina', topics:['movimenti sociali','ecologia','femminismo','lavoro'], active:true },
    headlines: [
      { title:'Il PP ottiene una vittoria insufficiente, Vox frena la sua crescita e il PSOE resiste', summary:'Analisi dei risultati in Castiglia e León: il PP vince ma non basta, Vox rallenta, PSOE tiene.', url:'https://www.elsaltodiario.com/castilla-y-leon/resultados-elecciones-2026', topic:'politica', pubDate:`${TODAY}T09:30:00Z` },
      { title:'Né resa né accordo: la guerra in Iran entra nella sua terza settimana senza via d\'uscita', summary:"Il conflitto in Iran prosegue senza segnali di risoluzione o accordi tra le parti.", url:'https://www.elsaltodiario.com/iran/guerra-iran-tercera-semana', topic:'conflitti', pubDate:`${TODAY}T08:45:00Z` },
      { title:'Il continente africano sotto scacco a causa della guerra in Iran', summary:"Le ripercussioni del conflitto iraniano sul continente africano: fertilizzanti bloccati, carburante razionato.", url:'https://www.elsaltodiario.com/actualidad-africana/continente-africano-jaque-guerra-iran', topic:'geopolitica', pubDate:`${TODAY}T08:00:00Z` },
      { title:"L'altro fronte: come Israele sta sfruttando la guerra per aumentare la violenza in Cisgiordania", summary:'Israele usa il contesto bellico per intensificare gli attacchi e le restrizioni nei territori palestinesi.', url:'https://www.elsaltodiario.com/palestina/otro-frente-israel-violencia-cisjordania', topic:'conflitti', pubDate:`${TODAY}T07:30:00Z` },
      { title:"Un'azione contro gli affitti turistici blocca 450 serrature nei quartieri di València", summary:"A Valencia, una protesta ha reso inutilizzabili 450 serrature di proprietà destinate agli affitti turistici.", url:'https://www.elsaltodiario.com/valencia/accion-alquiler-turistico-cerraduras', topic:'società', pubDate:`${TODAY}T07:00:00Z` },
      { title:'Maiorca: la piattaforma democratica vuole annullare l\'abrogazione della Legge sulla Memoria Storica', summary:"Una piattaforma civica spera di invalidare l'abrogazione della Legge sulla Memoria Storica.", url:'https://www.elsaltodiario.com/baleares/memoria-historica-mallorca', topic:'diritti', pubDate:`${TODAY}T06:30:00Z` },
      { title:'Sciopero dei rider a Madrid: "Ci trattano come macchine"', summary:'I fattorini di Glovo e Deliveroo scioperano per il terzo giorno consecutivo chiedendo contratti regolari.', url:'https://www.elsaltodiario.com/trabajo/huelga-riders-madrid', topic:'lavoro', pubDate:`${TODAY}T06:00:00Z` },
      { title:'L\'agenzia climatica europea lancia l\'allarme siccità: 2026 anno peggiore del decennio', summary:'I dati di Copernicus mostrano che la primavera 2026 si profila come la più secca degli ultimi dieci anni in Europa meridionale.', url:'https://www.elsaltodiario.com/medioambiente/sequia-europa-2026-copernicus', topic:'clima', pubDate:`${TODAY}T05:30:00Z` },
      { title:'Chi sono i militanti di Sumar che si dimettono dopo la crisi interna', summary:'Diversi esponenti di Sumar lasciano il partito dopo le tensioni post-elettorali con Podemos e i movimenti sociali.', url:'https://www.elsaltodiario.com/politica/dimisiones-sumar-crisis-interna', topic:'politica', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Il femminismo spagnolo si divide sull\'astensione nelle regionali', summary:'Dibattito acceso nei movimenti femministi dopo che alcune figure storiche hanno invitato all\'astensione nelle elezioni di Castiglia e León.', url:'https://www.elsaltodiario.com/feminismo/debate-abstencion-castilla-leon', topic:'diritti', pubDate:`${TODAY}T04:30:00Z` },
    ]
  },
  {
    newspaper: { id:'7', slug:'la-jornada', name:'La Jornada', country:'MX', region:'america-latina', language:'es', orientation:'sinistra', frequency:'daily', description:'Quotidiano messicano di sinistra. Storico, fondato nel 1984.', url:'https://www.jornada.com.mx', rss_url:'https://www.jornada.com.mx/rss/edicion.xml', scrape_method:'rss', topics:['politica','economia','indigeni'], active:true },
    headlines: [
      { title:'Editoriale: Tutta la solidarietà per Cuba', summary:'Annunciate conversazioni ufficiali tra Cuba e USA dopo mesi di blocco imposto da Trump.', url:'https://www.jornada.com.mx/2026/03/16/opinion/002a1edi', topic:'geopolitica', pubDate:`${TODAY}T07:00:00Z` },
      { title:'Rapporto ONG: Il governo USA ha forzato migranti in altri paesi', summary:"22 ONG denunciano la strategia di deportazione e trasferimento forzato di richiedenti asilo da parte di Trump.", url:'https://www.jornada.com.mx/2026/03/16/politica/008n1pol', topic:'diritti', pubDate:`${TODAY}T06:45:00Z` },
      { title:'Carlos Fazio: L\'Iran resiste e contrattacca', summary:'La "guerra imperialista" di USA e Israele contro l\'Iran, prevista breve, è giunta alla sua terza settimana.', url:'https://www.jornada.com.mx/2026/03/16/politica/015a2pol', topic:'conflitti', pubDate:`${TODAY}T06:30:00Z` },
      { title:'WSJ: USA aveva un rapporto da ex dirigente Chevron prima del "rapimento" di Maduro', summary:"Un ex dirigente Chevron ha collaborato come informatore della CIA prima del presunto rapimento di Maduro.", url:'https://www.jornada.com.mx/2026/03/16/mundo/022n1mun', topic:'investigazione', pubDate:`${TODAY}T06:15:00Z` },
      { title:"L'INE, secondo ramo autonomo più oneroso per il bilancio federale", summary:"L'Istituto Nazionale Elettorale ha ricevuto oltre 242 miliardi di pesos dal 2018, risultando il secondo più costoso.", url:'https://www.jornada.com.mx/2026/03/16/politica/007n1pol', topic:'politica', pubDate:`${TODAY}T06:00:00Z` },
      { title:'Comunità zapatiste: "La guerra in Iran non è lontana, è la stessa logica"', summary:"Un comunicato dell'EZLN traccia un parallelo tra la guerra contro l'Iran e la violenza subita dai popoli indigeni.", url:'https://www.jornada.com.mx/2026/03/16/politica/zapatistas-iran', topic:'geopolitica', pubDate:`${TODAY}T05:45:00Z` },
      { title:'Messico: il peso si stabilizza nonostante la crisi dello Hormuz', summary:'Il peso messicano regge meglio del previsto grazie alla diversificazione delle esportazioni energetiche verso l\'Asia.', url:'https://www.jornada.com.mx/2026/03/16/economia/peso-hormuz', topic:'economia', pubDate:`${TODAY}T05:30:00Z` },
      { title:'Claudia Sheinbaum firma la riforma per i diritti delle lavoratrici domestiche', summary:'La presidente messicana firma la legge che estende la previdenza sociale e il salario minimo alle lavoratrici domestiche.', url:'https://www.jornada.com.mx/2026/03/16/politica/sheinbaum-trabajadoras-domesticas', topic:'lavoro', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Il Messico richiama l\'ambasciatore in Israele per le operazioni in Libano', summary:'In risposta ai bombardamenti su Beirut, il Messico richiama il proprio ambasciatore "per consultazioni".',  url:'https://www.jornada.com.mx/2026/03/16/mundo/mexico-embajador-israel', topic:'geopolitica', pubDate:`${TODAY}T04:30:00Z` },
      { title:'Crisi idrica in Monterrey: terzo anno consecutivo di razionamento', summary:"La metropoli industriale del nord affronta il terzo anno di razionamento dell'acqua con riserve ai minimi storici.", url:'https://www.jornada.com.mx/2026/03/16/estados/crisis-agua-monterrey', topic:'clima', pubDate:`${TODAY}T04:00:00Z` },
    ]
  },
  {
    newspaper: { id:'18', slug:'the-guardian', name:'The Guardian', country:'UK', region:'uk-us', language:'en', orientation:'progressista', frequency:'continuous', description:'Quotidiano britannico progressista.', url:'https://www.theguardian.com', rss_url:'https://www.theguardian.com/world/rss', scrape_method:'rss', topics:['politica','clima','diritti'], active:true },
    headlines: [
      { title:"L'Africa particolarmente vulnerabile per l'interruzione delle catene di approvvigionamento durante il conflitto Iran", summary:"L'agricoltura africana dipende pesantemente dai fertilizzanti del Golfo: molto esposta alle interruzioni del conflitto.", url:'https://www.theguardian.com/world/2026/mar/16/africa-vulnerable-iran-conflict-supply-chains', topic:'geopolitica', pubDate:`${TODAY}T10:00:00Z` },
      { title:"La Francia restituisce un tamburo sacro saccheggiato dalla Costa d'Avorio oltre 100 anni fa", summary:"Il Djidji Ayôkwé torna alla Costa d'Avorio: una delle più significative restituzioni culturali degli ultimi anni.", url:'https://www.theguardian.com/world/2026/mar/13/france-returns-sacred-djidji-ayokwe-talking-drum', topic:'cultura', pubDate:'2026-03-13T14:00:00Z' },
      { title:'Il governo del Regno Unito taglia un progetto di punta per la salute globale', summary:"Un importante programma sanitario in Africa, elogiato come protezione contro future pandemie, tagliato per i tagli agli aiuti.", url:'https://www.theguardian.com/global-development/2026/mar/12/uk-axes-global-health-project', topic:'politica', pubDate:'2026-03-12T16:00:00Z' },
      { title:'Attivista ambientale in Honduras: l\'ICE ha deportato il marito nonostante le minacce di morte', summary:"Una famiglia attivista fuggita dall'Honduras ha visto il marito deportato dall'ICE, lasciandolo solo in Honduras.", url:'https://www.theguardian.com/us-news/ng-interactive/2026/mar/13/honduras-family-deportation', topic:'diritti', pubDate:'2026-03-13T12:00:00Z' },
      { title:'Cinque arresti a Cuba dopo protesta presso un ufficio del partito comunista', summary:"Cinque persone arrestate per una rara protesta presso un ufficio del partito comunista cubano degenerata in incendi.", url:'https://www.theguardian.com/world/2026/mar/14/arrests-cuba-communist-party-protest', topic:'politica', pubDate:'2026-03-14T18:00:00Z' },
      { title:'La sorveglianza di massa guidata dall\'IA in Africa viola le libertà, avvertono gli esperti', summary:"Sistemi AI di sorveglianza di massa in Africa stanno violando la privacy con effetto raggelante sulla società civile.", url:'https://www.theguardian.com/global-development/2026/mar/12/invasive-ai-surveillance-africa', topic:'diritti', pubDate:'2026-03-12T08:00:00Z' },
      { title:'Il mercato nigeriano dei creator è esploso: riusciranno a monetizzare?', summary:'Nonostante la crescita, i creator nigeriani faticano a monetizzare per la diminuzione dei ricavi pubblicitari.', url:'https://www.theguardian.com/media/2026/mar/15/nigerias-content-creator-market', topic:'economia', pubDate:'2026-03-15T10:00:00Z' },
      { title:'Eswatini conferma altri deportati "di terzi paesi" dall\'accordo Trump', summary:"Il governo dell'Eswatini ha ricevuto quattro nuovi deportati USA nell'ambito del controverso accordo multimilionario.", url:'https://www.theguardian.com/us-news/2026/mar/12/trump-deportations-eswatini', topic:'migrazioni', pubDate:'2026-03-12T20:00:00Z' },
      { title:'Il Sudan registra il peggior anno di sfollamenti dalla fine della guerra fredda', summary:'L\'ONU avverte: oltre 14 milioni di sfollati interni in Sudan nel 2025, il dato peggiore da decenni.', url:'https://www.theguardian.com/world/2026/mar/15/sudan-displacement-crisis', topic:'conflitti', pubDate:'2026-03-15T14:00:00Z' },
      { title:'COP32 a rischio: i paesi produttori di petrolio chiedono rinvio causa guerra in Iran', summary:"Arabia Saudita e UAE premono per un rinvio della conferenza sul clima, citando l'instabilità geopolitica.", url:'https://www.theguardian.com/environment/2026/mar/16/cop32-delay-iran-oil-producers', topic:'clima', pubDate:`${TODAY}T09:00:00Z` },
    ]
  },
  {
    newspaper: { id:'19', slug:'al-jazeera', name:'Al Jazeera', country:'QA', region:'medio-oriente', language:'en', orientation:'indipendente', frequency:'continuous', description:'Copertura Africa, Medio Oriente, Asia. Alternativa a CNN/BBC.', url:'https://www.aljazeera.com', rss_url:'https://www.aljazeera.com/xml/rss/all.xml', scrape_method:'rss', topics:['geopolitica','medio-oriente','africa','conflitti'], active:true },
    headlines: [
      { title:"Stretto di Hormuz: a quali navi l'Iran ha concesso il passaggio sicuro?", summary:'Teheran consente a un numero limitato di navi di alcuni paesi di attraversare il canale navigabile.', url:'https://www.aljazeera.com/economy/2026/3/16/strait-of-hormuz-safe-passage', topic:'geopolitica', pubDate:`${TODAY}T11:00:00Z` },
      { title:"In Libano, Israele usa l'occupazione come strumento di negoziazione", summary:"Israele usa l'occupazione militare del Libano meridionale per dettare i termini del cessate il fuoco.", url:'https://www.aljazeera.com/features/2026/3/16/lebanon-israel-occupation-negotiating-tool', topic:'conflitti', pubDate:`${TODAY}T10:30:00Z` },
      { title:"Guerra contro l'Iran: il razionamento del carburante può alleviare i problemi petroliferi?", summary:"L'aumento dei prezzi del petrolio sta spingendo le nazioni a riadeguare le loro politiche energetiche.", url:'https://www.aljazeera.com/news/2026/3/16/iran-war-fuel-rationing', topic:'economia', pubDate:`${TODAY}T10:00:00Z` },
      { title:'Il parlamento del Myanmar, dominato dal partito filo-militare, si riunisce dopo 5 anni', summary:'Il nuovo parlamento si apre per la prima volta dal colpo di stato del 2021 dopo elezioni che hanno escluso i principali partiti.', url:'https://www.aljazeera.com/news/2026/3/16/myanmar-parliament-convenes', topic:'politica', pubDate:`${TODAY}T09:30:00Z` },
      { title:'Distruzione a Beirut mentre bombardamenti e sfollamenti di massa continuano', summary:'I quartieri nella periferia meridionale di Beirut sono stati ridotti in macerie dagli attacchi aerei israeliani.', url:'https://www.aljazeera.com/video/2026/3/16/destruction-beirut-bombing', topic:'conflitti', pubDate:`${TODAY}T09:00:00Z` },
      { title:'La Cina offre mediazione nel conflitto Iran-USA: Pechino convoca entrambe le parti', summary:'In un insolito gesto diplomatico, la Cina invita rappresentanti di USA e Iran a colloqui di pace a Shanghai.', url:'https://www.aljazeera.com/news/2026/3/16/china-mediation-iran-usa', topic:'geopolitica', pubDate:`${TODAY}T08:30:00Z` },
      { title:'Gaza: il sistema sanitario al collasso dopo tre settimane di blocco israeliano', summary:"L'unico ospedale ancora funzionante a Gaza nord segnala l'esaurimento dei medicinali e dei generatori.", url:'https://www.aljazeera.com/news/2026/3/16/gaza-health-system-collapse', topic:'diritti', pubDate:`${TODAY}T08:00:00Z` },
      { title:'Protestatari in Corea del Sud contro la richiesta USA di pattugliare lo Hormuz', summary:'Decine di migliaia di persone scendono in piazza a Seul contro il coinvolgimento della Marina sudcoreana nel conflitto.', url:'https://www.aljazeera.com/news/2026/3/16/south-korea-protests-hormuz', topic:'politica', pubDate:`${TODAY}T07:30:00Z` },
      { title:'Le donne yemenite guida le truppe Houthi nello Stretto di Bab-el-Mandeb', summary:'Un reportage sul campo sui battaglioni femminili Houthi che presidiano le acque del Mar Rosso.', url:'https://www.aljazeera.com/features/2026/3/16/yemen-houthi-women-fighters', topic:'conflitti', pubDate:`${TODAY}T07:00:00Z` },
      { title:'Il presidente sudanese deposto Bashir muore in prigione a 82 anni', summary:'Omar al-Bashir, ricercato dalla Corte Penale Internazionale, è deceduto nel carcere di Kobar a Khartoum.', url:'https://www.aljazeera.com/news/2026/3/16/bashir-dies-prison-sudan', topic:'politica', pubDate:`${TODAY}T06:30:00Z` },
    ]
  },
  {
    newspaper: { id:'21', slug:'the-intercept', name:'The Intercept', country:'US', region:'uk-us', language:'en', orientation:'sinistra-investigativo', frequency:'regular', description:'Fondato da Greenwald. Sicurezza nazionale, sorveglianza, diritti civili.', url:'https://theintercept.com', rss_url:'https://theintercept.com/feed/?rss', scrape_method:'rss', topics:['sorveglianza','diritti civili','politica estera'], active:true },
    headlines: [
      { title:'Il Blocco Israeliano Intrappola 7 Medici Statunitensi a Gaza', summary:'Sette medici statunitensi bloccati a Gaza dalla sospensione dei viaggi imposta da Israele, mettendo a rischio i pazienti.', url:'https://theintercept.com/2026/03/13/israel-blockade-gaza-doctors/', topic:'conflitti', pubDate:'2026-03-13T14:00:00Z' },
      { title:'Manifestanti Anti-ICE Condannati per Terrorismo per Aver Indossato Abiti Neri', summary:'Il governo condanna manifestanti anti-ICE per terrorismo, anche per aver indossato abiti neri.', url:'https://theintercept.com/2026/03/13/ice-protesters-terrorism/', topic:'diritti', pubDate:'2026-03-13T12:00:00Z' },
      { title:"Nella Stanza Dove i Condannati a Morte Dicono Addio, Ha Scoperto Che Avrebbe Vissuto", summary:"Un giornalista doveva testimoniare un'esecuzione ma ha assistito alla commutazione della pena.", url:'https://theintercept.com/2026/03/14/alabama-execution-commutation/', topic:'diritti', pubDate:'2026-03-14T16:00:00Z' },
      { title:"Perché i Democratici Non Chiedono la Fine della Guerra con l'Iran", summary:"I Democratici preferiscono critiche procedurali all'opposizione morale alla guerra con l'Iran.", url:'https://theintercept.com/2026/03/13/iran-war-democrats/', topic:'politica', pubDate:'2026-03-13T10:00:00Z' },
      { title:"La Cripto Spende Milioni nell'Illinois per Diffamare i Sostenitori dei Diritti dei Consumatori", summary:"Un PAC delle criptovalute spende milioni per diffamare progressisti nelle primarie dell'Illinois.", url:'https://theintercept.com/2026/03/15/crypto-illinois-primaries/', topic:'politica', pubDate:'2026-03-15T11:00:00Z' },
      { title:'Il Pentagono Nasconde i Dati sulle Vittime Civili nei Raid in Iran', summary:'Documenti ottenuti via FOIA rivelano che il Pentagono sta classificando le stime di vittime civili degli attacchi in Iran.', url:'https://theintercept.com/2026/03/14/pentagon-civilian-casualties-iran/', topic:'investigazione', pubDate:'2026-03-14T18:00:00Z' },
      { title:'La Casa Bianca Usa Legge del 1798 per Detenere Attivisti Anti-Guerra Senza Processo', summary:"L'amministrazione Trump ha invocato lo Alien Enemies Act per trattenere cittadini stranieri coinvolti nelle proteste anti-guerra.", url:'https://theintercept.com/2026/03/15/alien-enemies-act-antiwar-activists/', topic:'diritti', pubDate:'2026-03-15T14:00:00Z' },
      { title:'NSA Amplia la Sorveglianza delle Comunicazioni con il Medio Oriente', summary:'Nuovi documenti mostrano che l\'NSA ha ottenuto dal FISA Court poteri di sorveglianza estesi su tutto il traffico da/per i paesi mediorientali.', url:'https://theintercept.com/2026/03/16/nsa-surveillance-middle-east/', topic:'sorveglianza', pubDate:`${TODAY}T09:00:00Z` },
      { title:'I Contractor Privati della Guerra in Iran: Chi Guadagna dal Conflitto', summary:'Un\'inchiesta sui contractor militari privati che hanno incassato contratti per miliardi nelle prime settimane della guerra.', url:'https://theintercept.com/2026/03/15/iran-war-contractors-profits/', topic:'investigazione', pubDate:'2026-03-15T16:00:00Z' },
      { title:'Dem in Maine: soldi del PAC finiti ai repubblicani', summary:'Un candidato democratico nelle primarie del Maine ha canalizzato fondi PAC verso candidati repubblicani in distretti chiave.', url:'https://theintercept.com/2026/03/15/maine-dem-pac-republicans/', topic:'politica', pubDate:'2026-03-15T08:00:00Z' },
    ]
  },
  {
    newspaper: { id:'22', slug:'jacobin', name:'Jacobin', country:'US', region:'uk-us', language:'en', orientation:'sinistra-intellettuale', frequency:'daily', description:'Rivista socialista americana. Analisi di classe, lavoro, politica.', url:'https://jacobin.com', rss_url:'https://jacobin.com/feed/', scrape_method:'rss', topics:['socialismo','lavoro','politica','economia'], active:true },
    headlines: [
      { title:'Jürgen Habermas ha mostrato cosa può essere la filosofia', summary:"Necrologio e analisi dell'eredità di Habermas, scomparso a novantasei anni.", url:'https://jacobin.com/2026/03/habermas-obituary/', topic:'cultura', pubDate:`${TODAY}T08:00:00Z` },
      { title:'La "classe Epstein" indaga su sé stessa', summary:"Un procuratore federale con conflitti d'interessi gestisce le più importanti indagini degli USA.", url:'https://jacobin.com/2026/03/epstein-class-corruption/', topic:'investigazione', pubDate:`${TODAY}T07:30:00Z` },
      { title:"I socialisti hanno bisogno di un'agenda economica distintiva", summary:"L'urgenza per i socialisti USA di sviluppare una chiara agenda di politica economica alternativa.", url:'https://jacobin.com/2026/03/socialist-economic-agenda/', topic:'politica', pubDate:`${TODAY}T07:00:00Z` },
      { title:'Come un omicidio politico ha dominato le elezioni municipali francesi', summary:"L'impatto inatteso dell'omicidio di Deranque sulle elezioni comunali francesi.", url:'https://jacobin.com/2026/03/france-political-killing-elections/', topic:'politica', pubDate:`${TODAY}T06:30:00Z` },
      { title:"L'estrema destra europea vuole essere vassalla americana", summary:"L'estrema destra europea si allinea agli USA nonostante la retorica sovranista.", url:'https://jacobin.com/2026/03/europe-far-right-vassals/', topic:'politica', pubDate:`${TODAY}T06:00:00Z` },
      { title:'La Festa di San Patrizio di Trump Sarà una Celebrazione della Guerra', summary:"L'evento alla Casa Bianca diventa occasione di propaganda pro-guerra con ospiti del complesso militare-industriale.", url:'https://jacobin.com/2026/03/trump-st-patricks-day-war/', topic:'politica', pubDate:`${TODAY}T05:30:00Z` },
      { title:'Il sindacato degli insegnanti di New York sfida il taglio ai fondi sull\'istruzione', summary:"Gli insegnanti di NYC minacciano lo sciopero dopo i tagli federali all'istruzione pubblica decisi dall'amministrazione Trump.", url:'https://jacobin.com/2026/03/nyc-teachers-union-education-cuts/', topic:'lavoro', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Come i BRICS stanno rispondendo alla guerra in Iran', summary:"Le nazioni BRICS si muovono in ordine sparso: Russia e Cina resistono alle sanzioni, India e Brasile cercano mediazione.", url:'https://jacobin.com/2026/03/brics-iran-war-response/', topic:'geopolitica', pubDate:`${TODAY}T04:30:00Z` },
      { title:'Il "socialismo di emergenza" nella storia americana: i precedenti di Roosevelt e Nixon', summary:"Un'analisi storica dei momenti in cui il governo americano ha adottato misure di pianificazione economica in tempo di crisi.", url:'https://jacobin.com/2026/03/emergency-socialism-us-history/', topic:'economia', pubDate:`${TODAY}T04:00:00Z` },
      { title:'Amazon licenzia 12.000 lavoratori di magazzino mentre i profitti toccano il massimo storico', summary:"Amazon annuncia la più grande ondata di licenziamenti nella logistica mentre registra utili record per il terzo trimestre consecutivo.", url:'https://jacobin.com/2026/03/amazon-layoffs-warehouse-workers/', topic:'lavoro', pubDate:'2026-03-15T20:00:00Z' },
    ]
  },
  {
    newspaper: { id:'23', slug:'972-magazine', name:'+972 Magazine', country:'IL/PS', region:'medio-oriente', language:'en', orientation:'progressista-critico', frequency:'regular', description:"Magazine israelo-palestinese. Voci critiche dall'interno del conflitto.", url:'https://www.972mag.com', rss_url:'https://www.972mag.com/feed/', scrape_method:'rss', topics:['israele-palestina','diritti umani','occupazione'], active:true },
    headlines: [
      { title:'La guerra è tra Israele e Iran. Perché la gente di Gaza dovrebbe pagarne il prezzo?', summary:"Dopo le chiusure dei valichi, i continui attacchi israeliani fanno temere un nuovo assalto su larga scala.", url:'https://www.972mag.com/gaza-iran-war-price/', topic:'conflitti', pubDate:`${TODAY}T09:00:00Z` },
      { title:'"La nostra copertura non è veritiera": come Israele censura i reportage sulla guerra', summary:"Ai giornalisti è impedito di pubblicare dettagli sui missili iraniani: l'intera storia non può essere raccontata.", url:'https://www.972mag.com/israel-media-censorship-iran-war/', topic:'diritti', pubDate:`${TODAY}T08:30:00Z` },
      { title:'La rinnovata guerra di Israele in Libano è più che solo Hezbollah', summary:"Dopo 10.000 violazioni del cessate il fuoco, Israele bombarda di nuovo il Libano con ambizioni crescenti.", url:'https://www.972mag.com/israel-lebanon-war-hezbollah/', topic:'conflitti', pubDate:`${TODAY}T08:00:00Z` },
      { title:'Il paradosso iraniano di Israele', summary:'Finché l\'occupazione persiste, eliminare un nemico crea solo la necessità di un altro.', url:'https://www.972mag.com/israel-iran-paradox/', topic:'geopolitica', pubDate:`${TODAY}T07:30:00Z` },
      { title:'Con la Cisgiordania sotto chiusura totale, i coloni approfittano del momento', summary:"Coloni israeliani hanno ucciso due palestinesi e saccheggiato decine di villaggi durante la guerra con l'Iran.", url:'https://www.972mag.com/west-bank-settler-violence-iran/', topic:'conflitti', pubDate:`${TODAY}T07:00:00Z` },
      { title:'"Il nostro vicinato non esiste più": storie da Beirut sotto le bombe', summary:'Reportage dai quartieri del sud di Beirut dove decine di migliaia di persone sono fuggite lasciando tutto.', url:'https://www.972mag.com/beirut-south-displacement-stories/', topic:'conflitti', pubDate:`${TODAY}T06:30:00Z` },
      { title:'La sinistra israeliana in crisi: chi si oppone alla guerra rischia la galera', summary:"Con la legge sui 'difensori di nemici', chiunque critichi l'operazione militare rischia fino a 15 anni.", url:'https://www.972mag.com/israeli-left-opposition-war-arrests/', topic:'diritti', pubDate:`${TODAY}T06:00:00Z` },
      { title:'Perché il Qatar medierà: interessi e rischi dello stato del Golfo', summary:"Il Qatar si trova in una posizione unica per mediare tra Iran e USA, ma rischia di pagare un prezzo alto per il suo ruolo.", url:'https://www.972mag.com/qatar-mediation-iran-usa-risks/', topic:'geopolitica', pubDate:`${TODAY}T05:30:00Z` },
      { title:'I beduini del Negev: dimenticate, le loro case vengono demolite anche durante la guerra', summary:"Mentre i media seguono i fronti di guerra, lo Stato israeliano continua a demolire le case beduine nel Negev.", url:'https://www.972mag.com/bedouin-negev-demolitions-war/', topic:'diritti', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Habermas e la questione israeliana: un lascito controverso', summary:"Riflessione sull'atteggiamento di Habermas verso Israele-Palestina alla luce della sua recente scomparsa.", url:'https://www.972mag.com/habermas-israel-palestine-legacy/', topic:'cultura', pubDate:`${TODAY}T04:30:00Z` },
    ]
  },
  {
    newspaper: { id:'26', slug:'daily-maverick', name:'Daily Maverick', country:'ZA', region:'africa', language:'en', orientation:'indipendente-progressista', frequency:'daily', description:'Sudafrica. Investigativo indipendente. BRICS dal lato africano.', url:'https://www.dailymaverick.co.za', rss_url:'https://www.dailymaverick.co.za/dmrss/', scrape_method:'rss', topics:['sudafrica','africa','BRICS','corruzione'], active:true },
    headlines: [
      { title:"Ex poliziotto d'élite accusato dell'omicidio di 'Testimone D' mentre la mente è a piede libero", summary:"Matipandile Sotheni, il presunto sicario, era stato addestrato dalla task force speciale d'élite della polizia.", url:'https://www.dailymaverick.co.za/article/elite-cop-witness-d-assassination/', topic:'investigazione', pubDate:`${TODAY}T09:00:00Z` },
      { title:'La Russia afferma di aver sventato il più grande attacco di droni ucraini in un anno', summary:"La Russia dichiara di aver abbattuto 250 droni ucraini verso Mosca nel fine settimana.", url:'https://www.dailymaverick.co.za/article/russia-ukraine-drone-attack/', topic:'conflitti', pubDate:`${TODAY}T08:30:00Z` },
      { title:'La Cina è in contatto con gli USA per il summit, le sanzioni contro Rubio potrebbero non essere applicabili', summary:"La Cina comunica con gli USA sul summit Trump e suggerisce che le sanzioni su Rubio non sono più in vigore.", url:'https://www.dailymaverick.co.za/article/china-us-summit-rubio-sanctions/', topic:'geopolitica', pubDate:`${TODAY}T08:00:00Z` },
      { title:"Ricordare Sharpeville è un invito a continuare la lotta contro il razzismo 'dilagante'", summary:"A 66 anni dal massacro, nuove prove suggeriscono che il bilancio delle vittime sia più alto di quanto riportato.", url:'https://www.dailymaverick.co.za/article/sharpeville-racism-struggle/', topic:'diritti', pubDate:`${TODAY}T07:30:00Z` },
      { title:"Il Vietnam si prepara a tagli ai voli dopo il divieto sull'esportazione di carburante di Cina e Thailandia", summary:"Le autorità vietnamite si preparano a potenziali riduzioni dei voli da aprile per il blocco del carburante jet.", url:'https://www.dailymaverick.co.za/article/vietnam-flight-cuts-fuel-ban/', topic:'economia', pubDate:`${TODAY}T07:00:00Z` },
      { title:'Il Sudafrica dichiara lo stato di emergenza nazionale per la siccità nel Capo Occidentale', summary:'Per la prima volta dal 2018, il governo sudafricano dichiara l\'emergenza siccità in due province del Capo.', url:'https://www.dailymaverick.co.za/article/south-africa-drought-emergency/', topic:'clima', pubDate:`${TODAY}T06:30:00Z` },
      { title:'I BRICS cercano di costruire un sistema di pagamento alternativo allo SWIFT', summary:'La riunione dei ministri delle finanze BRICS a Johannesburg accelera il progetto di un sistema di pagamento indipendente dal dollaro.', url:'https://www.dailymaverick.co.za/article/brics-payment-system-swift/', topic:'economia', pubDate:`${TODAY}T06:00:00Z` },
      { title:'ANC perde altri due comuni nelle elezioni suppletive: trend preoccupante', summary:"L'ANC cede altri due comuni nelle elezioni locali suppletive, segnalando un'ulteriore erosione del voto tradizionale.", url:'https://www.dailymaverick.co.za/article/anc-loses-municipalities-by-elections/', topic:'politica', pubDate:`${TODAY}T05:30:00Z` },
      { title:'La guerra in Iran fa salire il prezzo del petrolio: impatto sui trasporti africani', summary:"L'aumento del prezzo del petrolio greggio colpisce duramente i paesi africani importatori, dove i trasporti assorbono il 40% del PIL.", url:'https://www.dailymaverick.co.za/article/iran-oil-price-africa-transport/', topic:'economia', pubDate:`${TODAY}T05:00:00Z` },
      { title:'Processo Zuma: nuova udienza rinviata a causa di "minacce di sicurezza" non specificate', summary:"L'ennesimo rinvio nel processo all'ex presidente Zuma per corruzione, questa volta per presunte minacce alla sicurezza.", url:'https://www.dailymaverick.co.za/article/zuma-trial-postponed-security-threats/', topic:'investigazione', pubDate:`${TODAY}T04:30:00Z` },
    ]
  },
]
